### ISSUE TITLE
проблема с pip и psycorg

### ISSUE THREAD

**Issue by riangry** [alexey-goloburdin/django-clean-template#7]
в install.sh установка пакетов идет через pip(python2.x) , а не через pip3 (python3.x) и в requirements.txt указан psycorg2 с которым могут возникнуть проблемы при установке , может лучше использовать уже скомпилированный psycopg2-binary?

**Comment by nucluster** [comment]
Когда активировано виртуальное окружение установка идет через команду pip, а не pip3.
